Added binary file to gitignore, separated files, removed global vars, fixed graceful shutdown, closed channel, HTTP codes
ko-oler/perx-test-task-progression pull request #1
Opened 2021-11-17 15:38 UTC by ko-oler

- added binary file to gitignore
- main.go was separated to 3 files: service, task, handlers
- removed global vars
- fixed graceful shutdown (added waitgroups, added context), used these articles as an example (https://www.rodrigoaraujo.me/posts/golang-pattern-graceful-shutdown-of-concurrent-events/, https://itnext.io/explain-to-me-go-concurrency-worker-pool-pattern-like-im-five-e5f1be71e2b0)
- closed channel "chtasks"
- added HTTP codes in handlers

2021-11-17 15:43 UTC, aslobanova requested changes
Приехал .DS_store

2021-11-19 17:07 UTC, softzilla requested changes

2021-11-19 17:07 UTC, softzilla commented on handlers.go
> +func (tl *TaskList) GetListHandler(w http.ResponseWriter, r *http.Request) {
taskList - нарушает SOLID (S - Single Responsobility) - он и handlers он и логика вычисления, это плохо. Важно не только разнести по файлам, но и разделить логику - один объект это хандлеры (можно и без объекта если хочется) и другой объект логика

2021-12-10 06:28 UTC, aslobanova approved these changes

2021-12-10 06:28 UTC, merged